### ISSUE TITLE
方程式有多组解的时程序报错退出

### ISSUE THREAD

**Issue by kaguya05** [DuckSoft/GlockChem#14]

**Comment by kaguya05** [comment]
也就会出现类似这样的情况
正在检查配平...未配平
正在使用高斯消元引擎配平方程式...配平失败
由于无法对未配平的方程式进行相关的化学计算，系统自动退出。

**Comment by DuckSoft** [comment]
对于有多组解的方程式暂未支持直接计算。
以后将会采用其他机制令用户补充条件，直至条件数满足解方程之需。
