### ISSUE TITLE
关于数据库实现的问题

### ISSUE THREAD

**Issue by DuckSoft** [DuckSoft/GlockChem#15]
# 概况|Summary

拟为GlockChem设计一套用Java（ジャバ？）实现的多样化、可拓展的数据库。
设计完成，经讨论通过后，将在代码上给予实现。
# 要求|Requirements

数据库至少要支持下列特性：
- 多数据来源性：支持针对同种物质的同一属性从不同的数据来源获得信息
- 异步性、多线程性、线程安全性：数据库要能同时查询多个数据来源以获得数据，并以异步方式等待各自数据库引擎返回查询结果，同时这也要求了数据库需要具有线程安全性
- 可扩展性：支持用户增加数据来源（内置脚本引擎？）
- 多功能性：支持不同种类的数据（如溶解度、熔沸点等）
- 尽可能的平台无关性：尽量使用与平台无关的代码，实为不得已（如需直接操作本地数据文件）时，我们将本地特性封装在名为native的package中，并根据平台来调整代码。（最好不要出现这种情况）

**Comment by LionNatsu** [comment]
这是网络查询还是本地数据库？

**Comment by DuckSoft** [comment]
> 这是网络查询还是本地数据库？

当然都要有。

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by kaguya05** [comment]
利用cas号查询系统？

**Comment by LionNatsu** [comment]
Removed dup-comments.

**Comment by kaguya05** [comment]
。论手抽 不过是不是网络查询需要做本地缓存功能

**Comment by kaguya05** [comment]
。论手抽 不过是不是网络查询需要做本地缓存功能

**Comment by DuckSoft** [comment]
@kaguya05 

> 利用cas号查询系统？

首先，数据库本身的实现并不重要。在我们这种面向对象的开发过程中，我们需要做的是勾勒出程序的框架，而非如何去实现。
其次，网络查询的缓存与否，是由数据库引擎本身决定的，我们在这里要做的不是去写引擎，而是写一个能协调诸多数据库引擎运行的框架。

所以我认为暂时不必关注此问题。

**Comment by DuckSoft** [comment]
就我个人来看，问题的关键之处在于如何正确地协调稳定性和可拓展性。
诚然，如果把所有的数据库引擎（例如本地引擎和Wikipedia引擎）都嵌入到软件内部的话，软件的稳定性无疑是最高的，但这样做的同时也失去了可拓展性，而选择在软件内部嵌入能解析脚本语言的引擎来实现一些扩展的外部数据库查询，又会降低整体的鲁棒性。
虽然我对Jaba（更正：Java）研究不甚深入，但我个人感觉，在如此成熟的语言Java中，一定有某个机制能实现动态的代码加载和运行。就像Minecraft mod一样，我们完全可以把数据库引擎做成类似于mod的形式来给软件加载运行。

所以，@EAirPeter 求指教…
