### ISSUE TITLE
方程式配平中高斯消元后所得结果的处理？

### ISSUE THREAD

**Issue by DuckSoft** [DuckSoft/GlockChem#3]
# 背景

在 @EAirPeter 的奋斗下，通过高斯消元法配平方程式的算法已经基本完成。
然而，高斯消元法只能将一个满含系数的矩阵消成另一个矩阵，如下图：

> ![image](https://cloud.githubusercontent.com/assets/7822648/19019232/a5b2e922-88b2-11e6-8d7b-2faef2cd863b.png)

上图是有解的情况，而下图列出了两种没有解的情况：

> ![image](https://cloud.githubusercontent.com/assets/7822648/19019215/1eeb7cec-88b2-11e6-8bf1-5aced7fe4372.png)
# 问题

对于有解的情况，如何将所得矩阵转化为方程式的系数？
对于无解的情况，又该如何处理？

**Comment by LionNatsu** [comment]
Consider these situations:

```
(N := cols, M := rows)
N < M+1
N = M+1
N > M+1
```

**Comment by DuckSoft** [comment]
# 背景

伟大狮子 @LionNatsu 的“批判一番”。
（当然，没有钦定的意思QvQ）

> Consider these situations:
> 
> ```
> (N := cols, M := rows)
> N < M+1
> N = M+1
> N > M+1
> ```

## N < M+1

在进入分析之前，我们需要先明确一点——这个需要进行高斯消元的矩阵是从哪里来的？显然，这个矩阵是通过对某一未配平的方程式中的所有元素（或者叫原子？）运用质量守恒定律列出相应的方程而得到的。经过一番思索，我们不难得出结论：

> 由方程式所得矩阵的**行数**代表了该方程式所含**元素（或原子）的种类数**，所得矩阵的**列数**代表了该方程式所含**物质的种类数**。

将我们本段的标题——N < M+1用这句话来表达的话，就是：

> 方程式所含物质种类数小于方程式所含元素的种类数目+1。

显然，没有任何一个合理的方程式能满足这种要求。因为即使是最简单的单质变单质的方程式，如：

```
2O3 ===> 3O2
```

> 其中，物质种类 = 2，元素种类 = 1，满足N = M+1。
> 因此我们可以得出结论，这种状况是**不会出现的**。

更正：的确有这种情况的出现，例如：

```
KSO2 + ABCD = KSO2ABCD
```

正在修改代码中。

## N = M+1

这种情况是最为理想的状态，而恰巧所有的不需要引入其他参数来配平的方程式都满足这一点。
此时若所得矩阵为阶梯形矩阵（当然，没有标准形式中最下面的全0行），则配平系数有一组唯一确定的最小正整数解；其他情况对于我来说并不十分清楚，也许都是没有唯一解的情况吧。（求大神指点）

## N > M+1

这种情况下方程式有可能有一系列的解。通常情况下，如果没有再给定几组限制条件补全为N = M+1的情况，即使经过了高斯消元算法，所得结果矩阵仍然是一团糟。因此如果遭遇这种情况，我认为不需要进入高斯消元就可以将其排除在外。在程序中，可以考虑让用户补全到N = M+1再行判断。

# 小结

以上是我对狮子大神所提问题的一点分析。
很惭愧，就做了一点微小的工作，谢谢大家。

**Comment by LionNatsu** [comment]
The answer is right, the process is wrong.

> ## N < M+1
> 
> > 方程式所含物质种类数小于方程式所含元素的种类数目+1。
> 
> 显然，没有任何一个合理的方程式能满足这种要求。

Here is `KSO2 + ABCD = KSO2ABCD`.

**Comment by LionNatsu** [comment]
So that you should say, 'the result of Guassian, the "relevant" elements' count' , not 'the elements' count'.

**Comment by DuckSoft** [comment]
受教。正在修改代码中……

**Comment by DuckSoft** [comment]
@LionNatsu 感谢狮子的提醒，已发现一个重大bug并将其修复~
OAO
